title: Shen Zhuoran
email: cmsflash99@gmail.com
description: Personal site for Shen Zhuoran, an AI Resident at Google.
baseurl: ""
url: "https://cmsflash.github.io"
twitter_username: CMS_Flash
github_username:  cmsflash

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
