title: Shen Zhuoran
email: cmsflash99@gmail.com
description: Personal site for Shen Zhuoran, an AI researcher and a software engieer for self-driving.
baseurl: ""
url: "https://cmsflash.github.io"
twitter_username: CMS_Flash
github_username:  cmsflash

markdown: kramdown
remote_theme: jekyll/minima
google_analytics: G-6SRK9DNEMH

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-remote-theme
