# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Shen Zhuoran
email: cmsflash99@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal site for Shen Zhuoran, a Computer Science student at The University of Hong Kong.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cms-flash.github.io" # the base hostname & protocol for your site
asset_url: "../../../../../assets"
twitter_username: CMS_Flash
github_username: cms-flash

# Build settings
markdown: kramdown
